Repository micronaut-projects/micronaut-cassandra, pull requests merged in 2020-09, with the labels that each got.

#70 Dependency upgrades (Docs, tests)
  gradle.properties
Labels: type: dependency-upgrade

#72 doc: Add release history section
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#73 ci: set github core branch to 2.0.x
  gradle.properties
Labels: relates-to: build

#74 build: bump Driver For Apache Cassandra to 4.9.0
  gradle.properties
Labels: type: dependency-upgrade

#78 [cassandra] Update common files for branch 2.2.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#77 [cassandra] Update common files for branch master
  .github/workflows/gradle.yml
  config/HEADER
Labels: relates-to: build

#79 bump up micronaut test to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade
