Repository micronaut-projects/micronaut-cassandra, pull requests merged in 2022-07, with the labels that each got.

#258 bug: DependencyCheck is initialized at build time
  cassandra/src/main/resources/META-INF/native-image/io.micronaut.cassandra/cassandra/native-image.properties
Labels: relates-to: graal, type: bug

#261 build: bump Micronaut Framework to 3.5.3
  gradle.properties
Labels: type: dependency-upgrade

#262 build: adds BOM and Migration to Gradle Version Catalog
  .github/workflows/template-cleanup.yml
  cassandra-bom/build.gradle
  cassandra/build.gradle
  config/checkstyle/.rsync-filter
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
Labels: relates-to: build

#264 bug: Fix class initialized at build time
  cassandra/src/main/resources/META-INF/native-image/io.micronaut.cassandra/cassandra/native-image.properties
Labels: relates-to: graal, type: bug
