Repository micronaut-projects/micronaut-cassandra, pull requests merged in 2023-10, with the labels that each got.

#376 [cassandra] Update common files for branch master
  .editorconfig
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#360 Support multiple configurations in CassandraHealthIndicator.
  cassandra/src/main/java/io/micronaut/cassandra/health/CassandraHealthIndicator.java
  cassandra/src/test/groovy/io/micronaut/cassandra/health/CassandraHealthIndicatorSpec.groovy
  src/main/docs/guide/additional.adoc
  src/main/docs/guide/health.adoc
Labels: type: improvement

#377 Integrate with micronaut-micrometer.
  cassandra-bom/build.gradle
  cassandra/build.gradle
  cassandra/src/main/java/io/micronaut/cassandra/CassandraSessionFactory.java
  cassandra/src/main/java/io/micronaut/cassandra/metrics/CassandraMetricsBinder.java
  cassandra/src/test/groovy/io/micronaut/cassandra/metrics/CassandraMetricsSpec.groovy
  cassandra/src/test/resources/logback-test.xml
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/metrics.adoc
  src/main/docs/guide/toc.yml
  test-suite-cassandra-micrometer/build.gradle.kts
  test-suite-cassandra-micrometer/src/test/groovy/example/CassandraInfo.groovy
  test-suite-cassandra-micrometer/src/test/groovy/example/CassandraMetricsSpec.groovy
  test-suite-cassandra-micrometer/src/test/groovy/example/CassandraRepository.groovy
  test-suite-cassandra-micrometer/src/test/resources/application-test.properties
  test-suite-cassandra-micrometer/src/test/resources/logback-test.xml
Labels: type: enhancement
